version: 2
jobs:
  build:
    branches:
      only:
        - dev
        - master
        - restart
    docker:
      - image: circleci/php:7.3.9-fpm
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: ecommerce_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run:
          name: "install composer dependency"
          command: composer install
      - run:
          name: "Run tests"
          command: phpdbg -d memory_limit=512M -qrr vendor/bin/phpunit --coverage-html build/coverage-report
          path:  build/coverage-report
