<x-avored-field
    label="avored::system.comms.general_site_name"
    for="general_site_name"
>
    <x-avored-input
        name="general_site_name"
        autofocus="autofocus"
        :value="$configuration->getValue('general_site_name')"
    >
    </x-avored-input>
</x-avored-field>
